export enum ConvertingResultStatus {
  CONVERTED_SUCCESS = "CONVERTED_SUCCESS",
  CONVERTED_PARTIALLY = "CONVERTED_PARTIALLY",
  CONVERTING_FAIL = "CONVERTING_FAIL",
  CLIENT_FAIL = "CLIENT_FAIL",
  UNKNOWN = "UNKNOWN",
}
